const mapping_table = {
  "m": "Mile",
  "d": "Date and Time",
  "t": "Temperature",
  "c": "Cloud Cover",
  "t_1": "Tide Level",
  "o": "# of People",
  "o_1": "# of Dogs",
  "b": "Being Active on the Coast",
  "e": "Enjoying the Coast",
  "s": "Surfing",
  "f": "Fishing",
  "t_2": "Tidepooling",
  "k": "Kayaking or boating",
  "p": "Playing in the surf or sand",
  "p_1": "Playing in sand",
  "p_2": "Photography",
  "w": "Windsurfing",
  "o_2": "Other Activities",
  "c_1": "Concerns",
  "a": "Apparent violations",
  "d_1": "Disturbances",
  "c_2": "Cars/trucks parking",
  "a_1": "ATVs/OHVs parking",
  "r": "RVs/Buses parking",
  "c_3": "Cars/Trucks on beach, allowed",
  "a_2": "ATVs/OHVs on beach, allowed",
  "c_4": "Cars/Trucks on beach, prohibited",
  "a_3": "ATVs/OHVs on beach, prohibited",
  "c_5": "Comments on Human Activities",
  "l": "Living Wildlife",
  "t_3": "Total Dead Birds",
  "s_1": "Signs of Oiling",
  "e_1": "Entanglement",
  "l_1": "Leg bands, species names, and counts",
  "s_2": "Stranded Mammals Total",
  "s_3": "Stranded Mammals Description",
  "u": "Unusual Concentration",
  "u_1": "Unusual Fish Description",
  "w_1": "Wrack Line Content",
  "o_3": "Other",
  "n": "New Development",
  "o_4": "Other development",
  "m_1": "Modifications",
  "c_6": "Comments on modifications",
  "n_1": "Natural Changes",
  "o_5": "Other Natural Changes",
  "h": "Have you taken action on any of the above problems?",
  "a_4": "Actions and Comments",
  "s_4": "Summary",
  "r_1": "Report Gallery",
  "h_1": "How many hours did you spend walking this mile and completing this report?",
  "d_2": "Did you complete any other Community Science Activities during the taking of this report?",
  "p_3": "Protected Status",
  "i": "Interview"
};
