const mile_numbers = {
  1: "Winchuck River, Crissey Airport, California border",
  2: "McVay Creek, South of Red Point",
  3: "Harbor Beach south of Chetco River, north of Red Point",
  4: "North Jetty, Brookings Beach west of Chetco, Tanbark Point",
  5: "Chetco Point, Macklyn Cove, Mill Beach, Zwagg Island",
  7: "Ransom Creek, South Harris Beach SP",
  8: "Harris Beach SP picnic area, Goat Island",
  9: "Harris Beach SP, Shy Creek, Taylor Creek",
  10: "Rainbow Island, Lone Ranch Beach, Boardman SP",
  11: "Cape Ferrelo, Boardman SP, House Rock Creek",
  12: "Boardman SP cliffs",
  13: "Boardman SP, Whalehead Island, Bowman Creek, Beach",
  14: "Boardman SP, cliffs, Thomas Creek",
  15: "Boardman SP, China Creek, Spruce Creek",
  16: "Boardman SP, Natural Bridges, Miner Cr, Deer Pt, Arch Rock",
  17: "Boardman SP, Hooskanaden Creek, Whiskey Creek",
  18: "Boardman SP, Burnt Hill Creek, Fish Hatchery",
  20: "Saddle Rock, Crook Point",
  21: "Pistol River SP south",
  22: "Pistol River SP central",
  23: "Pistol River SP north, south of Myers Creek",
  24: "Cave Rock, Hunters Island, Hunters Cove",
  26: "Cape Sebastian SP, Buena Vista Wayside, S of Hunter Cr",
  27: "North of Hunter Creek, south of Gold Beach at Cunniff Cr",
  28: "Gold Beach Fairgrounds, airport, Rogue River South Jetty",
  29: "Rogue River North Jetty, Wedderburn, Knox Rock",
  30: "Bailey Beach south, Otter Point SP south",
  31: "Otter Point State Wayside, Bailey Beach",
  32: "Otter Point, Wayside north",
  33: "North of Otter Point, south of Hubbard Mound",
  34: "Wakeman Beach, Geisel Monument Wayside",
  35: "Nesika Beach, south of Ophir Safety Rest Area",
  36: "Nesika Beach, north of Ophir Rest Area, south of Euchre Cr",
  37: "Beach north of Euchre Creek, south of Devils Backbone",
  39: "Sisters Rocks",
  40: "North of Sisters Rocks, cliffs south of Arizona Beach",
  41: "Arizona Beach, Mussel Creek",
  42: "Lookout Rock, Reinhart Creek",
  43: "Beach south of Humbug Mountain",
  45: "South of Coal Point, north of Brush Creek",
  46: "Rocky Point, Betz Creek, north of Coal Point",
  47: "South of Hubbard Creek, north of Rocky Creek",
  48: "Beach southeast of Battle Rock, north of Hubbard Creek",
  49: "Graveyard Point, Port, Harbor, Battle Rock",
  50: "Port Orford Heads east of Tichenor Rock, Tichenor Cove",
  51: "Port Orford Heads west of Tichenor Rock",
  52: "Agate Beach, Garrison Lake, south of Paradise Point SW",
  53: "South of Elk River mouth, north of Paradise Point SW",
  54: "South of Cape Blanco, access road to Elk River",
  55: "South of Cape Blanco, north of CG beach access road",
  56: "Cape Blanco, Lighthouse",
  57: "North side of Cape Blanco, south of Castle Rock",
  58: "Floras Lake SP, between Castle Rock and Blacklock Pt",
  59: "Floras Lake SP, Blacklock Point",
  60: "Floras Lake SP, Floras Lake, Denmark",
  61: "west of New River, Floras Creek, Langlois",
  89: "west of New River, Morton. Curry/Coos county line",
  90: "west of New River, New Lake",
  93: "mouth of New River, Fourmile Creek",
  94: "west of Laurel Lake, Lost Lake",
  95: "south end of Bandon State Park",
  96: "Bandon State Park, west of Twomile Creek",
  97: "Bandon SP, between Twomile Cr and Bradley Lake",
  98: "Bandon State Park, China Creek",
  99: "Bandon State Park, Devils Kitchen, Haystack Rock",
  100: "Johnson Creek, Bandon Beach",
  101: "Face Rock, Bandon Beach, Coquille Point",
  102: "Coquille River, South Jetty, Lighthouse",
  103: "Bullards Beach just north of the Lighthouse",
  104: "Bullards Beach west of the Campground",
  105: "Bullards Beach, northwest of the Campground",
  106: "Bullards Beach, west of Fahys Lake",
  107: "Bullards Beach, Cut Creek, Chrome Lake, Round Lake",
  108: "South Whisky Run Beach",
  109: "Whisky Run, Fivemile Pt, south end Merchants Beach",
  110: "Merchants Beach, Seven Devils State Wayside",
  111: "Merchants Beach north end",
  112: "Agate Beach, Threemile Creek, south Sacchi Beach",
  113: "Fivemile Creek, north Sacchi Beach",
  116: "Seven Devils cliffs, Cape Arago South Cove",
  117: "Cape Arago, Drake Point, North Cove",
  118: "Cape Arago, Simpson Reef, Shell Island, Sea Lion Viewpoint",
  119: "Shore Acres SP, Simpson Cove",
  120: "Sunset Bay, Squaw Island",
  121: "Gregory Point, Lighthouse Beach, Mussel Reef",
  122: "Bastendorff Beach west half",
  123: "Bastendorff Beach east half, South Jetty Coos Bay",
  124: "South end of North Spit Coos Bay",
  125: "North Beach on North Spit Coos Bay",
  126: "North Beach on North Spit Coos Bay",
  127: "North Beach on North Spit Coos Bay",
  128: "North Beach on North Spit Coos Bay",
  129: "Horsfall Beach on North Spit, directly west of Jordan Cove",
  130: "Horsfall Beach, south end of Or Dunes Nat Rec Area",
  131: "Horsfall Beach, Oregon Dunes NRA",
  132: "Horsfall Beach, Oregon Dunes NRA west of Spirit Lake",
  133: "Horsfall Beach, Oregon Dunes NRA west of Snag Lake",
  134: "Horsfall Beach, Oregon Dunes NRA, west of Beale Lake, Hauser",
  135: "Oregon Dunes NRA, west of Beale Lake",
  136: "Oregon Dunes NRA, west of Saunders Lake",
  137: "Oregon Dunes NRA, west of \"[Coos]\" Clear Lake",
  138: "Oregon Dunes NRA, south of Tenmile Creek",
  139: "Oregon Dunes NRA, N of Tenmile Creek",
  140: "Oregon Dunes NRA, W of Eel Campgrounds",
  141: "Oregon Dunes NRA",
  142: "Oregon Dunes NRA, Coos/Douglas county line",
  143: "South Umpqua Lighthouse SP",
  144: "West of central Umpqua Lighthouse SP",
  145: "North Umpqua Lighthouse SP, south of Lake Marie",
  146: "North Jetty, South Jetty Umpqua River, Lighthouse",
  147: "Oregon Dunes NRA, North Spit Umpqua River, Winchester Bay",
  148: "Oregon Dunes NRA, south of Army Hill",
  149: "Oregon Dunes NRA, north of Army Hill",
  150: "Oregon Dunes NRA, south of Brushy Hill",
  151: "Oregon Dunes NRA, S of Threemile Cr, N of Brushy Hill",
  152: "Oregon Dunes NRA, north of Threemile Creek",
  153: "Oregon Dunes NRA, west of Threemile Lake",
  154: "Oregon Dunes NRA, west of Butterfly Lake",
  155: "Oregon Dunes NRA, Tahkenitch Creek",
  156: "Oregon Dunes NRA, over dunes from Tahkenitch Creek",
  157: "Oregon Dunes NRA, west of Perkins Lake",
  158: "Oregon Dunes NRA, west of south end of Carter Lake",
  159: "Oregon Dunes NRA, west of Carter Lake",
  160: "Oregon Dunes NRA just south of Siltcoos River",
  161: "Oregon Dunes NRA just north of Siltcoos River",
  162: "Oregon Dunes NRA, west of North Beach",
  163: "Oregon Dunes NRA, west of south end Woahink Lake",
  164: "Oregon Dunes NRA, W of Woahink Lake, Goose Pasture S",
  165: "Oregon Dunes NRA, W of Cleawox Lake, Goose Pasture N",
  166: "South Jetty Road ATV Staging Area",
  167: "South end Siuslaw South Jetty Road",
  168: "Central South Siuslaw Jetty Road",
  169: "North end Siuslaw South Jetty Road",
  170: "South end Heceta Beach, North and South Jetty Siuslaw R",
  171: "Heceta Beach South, almost to North Jetty",
  172: "Heceta Beach North, Driftwood Shores",
  173: "South end of Baker Beach, Sutton Creek, Heceta Beach",
  174: "Baker Beach west of Alder Dunes CG, north of Sutton Creek",
  175: "Baker Beach Road, Trail",
  176: "North end Baker Beach, Lily Lake",
  177: "Cliffs south of Horse Creek, north of Baker Beach",
  178: "Cape Cove, Sea Lion Point, Sea Lion Caves",
  179: "Heceta Head Lighthouse, Devils Elbow SP, Cape Creek",
  180: "South Carl G. Washburne SP, Hobbit Trail, Heceta Head",
  181: "Carl G. Washburne SP, Blowout Creek",
  182: "Roosevelt Beach, Ponsler SW, China Creek, Big Creek",
  183: "North end of Roosevelt Beach, Rock Creek, Rocky Knoll",
  184: "N of Ocean Beach Picnic Area, S of Squaw Creek",
  185: "S of Stonefield Beach Wayside, Tokatee Kloochman Wayside",
  186: "Tenmile Cr, Searose Beach N of Stonefield Beach Wayside",
  187: "Neptune SP, Bob Creek, Gwynn Knoll",
  188: "Neptune SP, Strawberry Hill Picnic Area",
  189: "Gwynn Cr, Neptune SP / North access, Cummins Cr",
  190: "Captain Cook Pt, Cooks Chasm, Cape Perpetua SRA, Cape Cr",
  191: "Devils Churn, Cape Perpetua, North Cape Creek",
  192: "Cape Perpetua north",
  193: "Yachats Ocean Road Wayside, Yachats SP",
  194: "Yachats, Adobe Inn, Smelt Sands Wayside",
  195: "South San Marine Beach, Starr Creek",
  196: "Vingie Creek, San Marine Beach south",
  197: "San Marine, Tillicum Beach, Tillicum Beach CG",
  198: "Beachside State Park to Reynolds Creek",
  199: "Beachside SP, Waconda Beach, Little Creek",
  200: "Big Stump Beach, south Patterson SP",
  201: "Patterson Memorial SP, Patterson Cr, Yaquina John Pt",
  202: "North Spit Alsea River",
  203: "Driftwood Beach south, Hidden Lake",
  204: "Driftwood Beach Wayside, Buckley Creek",
  205: "Driftwood Beach north, Collins Creek, Squaw Creek",
  206: "Seal Rock Wayside south, Elephant Rock, Hill Creek",
  207: "Seal Rock Wayside north, Seal Rocks, Deer Creek",
  208: "Ona Beach, south of Beaver Creek",
  209: "Ona Beach north of Beaver Creek, Tracy Creek",
  210: "Lost Creek Wayside south, Lost Creek",
  211: "Lost Creek Wayside north, Holiday Beach south",
  212: "Holiday Beach north, Moore Creek, Grant Creek",
  213: "Henderson Creek, South Beach SP south",
  214: "South Beach SP, South Jetty Yaquina River",
  215: "Yaquina Bay SP, North Jetty Yaquina River",
  216: "Newport, Nye Beach south",
  217: "Newport, Nye Beach north, Agate Beach south",
  218: "Agate Beach, State Wayside, Little Creek",
  219: "North end of Agate Beach, Yaquina Head south",
  220: "Yaquina Head north, Schooner Creek south",
  221: "Schooner Pt, Moolack Beach S of Moolack Creek",
  222: "Moolack Beach N, Coal Creek, S of Wade Creek",
  223: "Beverly Beach, Spencer Creek, Beverly Beach SP",
  224: "Beverly Beach north, Johnson Creek",
  225: "Otter Rock, Devils Punch Bowl SP",
  226: "Otter Crest, State Wayside",
  227: "Cape Foulweather, Rocky Creek",
  228: "Rocky Creek State Wayside, Whale Cove",
  229: "South Depoe Bay",
  230: "Depoe Bay, State Wayside",
  231: "Depoe Bay north, Pirate Cove",
  232: "Boiler Bay Wayside, Picnic Area, Government Point",
  233: "Boiler Bay, Rabbit Rock, Fogarty Creek SP",
  234: "Lincoln Beach",
  235: "Gleneden Beach south",
  236: "Gleneden Beach, State Wayside",
  237: "Gleneden Beach north, golf course",
  238: "Salishan Spit, North Lagoon, Siletz Bay",
  239: "Salishan Spit north, Siletz Bay",
  240: "Taft, Nelscott south, Baldy Creek",
  241: "Nelscott north, Lincoln City south",
  242: "Lincoln City, D River SW, Devils Lake SP, Oceanlake",
  243: "Wecoma Beach, Lincoln City",
  244: "Wecoma Beach north, Lincoln City, Roads End south",
  245: "Roads End Beach, Wayside, Logan Creek",
  246: "Cliffs north of Roads End Beach",
  247: "South Spit Salmon River, Tillamook/Lincoln county line",
  248: "Cascade Head south, Salmon River",
  249: "Cascade Head, Two Arches",
  250: "Cascade Head north, Cliff Creek",
  251: "Harts Cove, Chitwood Creek",
  252: "Neskowin Crest Research Natural Area, north",
  253: "Neskowin Beach, SW, Proposal Rock, Neskowin Creek",
  254: "Kiwanda Beach, Neskowin Crest",
  255: "Kiwanda Beach",
  256: "Kiwanda Beach, Daley Lake, Camp Winema",
  257: "Porter Point, Nestucca River",
  258: "Nestucca North Spit south end",
  259: "Nestucca Spit State Park, Kiwanda Beach",
  260: "Kiwanda Beach west of Pacific City and Nestucca River",
  261: "Haystack Rock, Cape Kiwanda",
  262: "Cape Kiwanda State Park",
  263: "Cape Kiwanda State Park north end",
  264: "Tierra Del Mar",
  265: "South Spit, Sand Lake",
  267: "Sand Beach south of Chamberlain Lake",
  269: "South of Cape Lookout, Camp Meriwether north, Rover Cr",
  270: "Cape Lookout south face",
  271: "Cape Lookout",
  272: "Cape Lookout north face",
  273: "Cape Lookout northeast, Cape Creek",
  274: "Cape Lookout SP",
  275: "South end Netarts Spit",
  276: "Netarts Spit south",
  277: "Netarts Spit",
  278: "Netarts Spit north",
  279: "Netarts Spit north end, Happy Camp",
  280: "North of Happy Camp, south of Oceanside",
  281: "Oceanside Beach, State Wayside, Agate Beach",
  282: "Lost Bay Cave, Short Beach",
  283: "Cape Meares, Refuge, Lighthouse, SP",
  284: "Cape Meares SP north",
  285: "Bayocean Peninsula, Cape Meares community and Lake",
  286: "Bayocean Peninsula south of Bayocean site",
  287: "Bayocean Peninsula north of Bayocean site",
  288: "Bayocean Peninsula, Kincheloe Point",
  289: "Kincheloe Point, South Jetty Tillamook River",
  290: "Barview Jetty County Park, Camp Magruder south",
  291: "Camp Magruder north, Watseco, Twin Rocks SW",
  292: "Twin Rocks, Heitmiller Creek",
  293: "Rockaway Beach, State Wayside",
  294: "Manhattan Beach, State Wayside",
  295: "Nedonna Beach",
  296: "South end Nehalem Beach, Nehalem Bay SP",
  297: "Nehalem Beach, Nehalem Bay SP",
  298: "Nehalem Beach, Nehalem Bay SP",
  299: "South end Manzanita Beach",
  300: "Manzanita Beach, Manzanita, Neahkahnie Beach",
  301: "Neahkahnie Beach north, Oswald West SP",
  302: "Oswald West SP, Neahkahnie Mountain, Devils Cauldron",
  303: "Oswald West SP, Smuggler Cove, Short Sand Beach",
  304: "Oswald West SP, Cape Falcon S",
  305: "Oswald West SP, Cape Falcon N",
  306: "Cove Beach south, Tillamook-Clatsop county line",
  307: "Cove Beach north, Arch Cape, Arch Cape Creek",
  308: "Arch Cape (community), Asbury Creek",
  309: "Austin Point, Hug Point SP, Arcadia Beach south",
  310: "Arcadia Beach N, Wayside, Lion Rock, Humbug Point",
  311: "Jockey Cap, Silver Pt, S Cannon Beach, Tolovana Beach",
  312: "Cannon Beach, Tolovana Park south",
  313: "Tolovana Park north, Haystack Rock",
  314: "Cannon Beach, Ecola Creek, Chapman Beach south",
  315: "Chapman Beach north, Chapman Point, Ecola SP",
  316: "Ecola Point, Bald Point",
  317: "Indian Beach, Canyon Creek, Indian Point",
  321: "West Point north, Ecola SP",
  322: "Seaside south",
  323: "Seaside",
  324: "Seaside north",
  325: "Clatsop Plains, Gearhart south",
  326: "Clatsop Plains, Gearhart Golf Course, Gearhart north",
  327: "Clatsop Plains",
  328: "Sunset Beach, Clatsop Plains",
  329: "Sunset Beach, Clatsop Plains, Sunset Lake",
  330: "Sunset Beach, Sunset Lake",
  331: "Sunset Beach, Slusher Lake, Camp Clatsop MR",
  332: "Columbia Beach, Camp Clatsop MR",
  333: "Columbia Beach, Camp Rilea MR",
  334: "Columbia Beach, Warrenton, Camp Rilea MR",
  335: "Columbia Beach, Coffenbury Lake, Fort Stevens SP",
  336: "Columbia Beach, Peter Iredale wreck, Fort Stevens SP",
  337: "Clatsop Spit, Swash Lake, Fort Stevens SP",
  338: "Clatsop Spit, Jetty Lagoon, Fort Stevens SP",
  339: "Clatsop Spit, Fort Stevens SP",
  340: "South Jetty Columbia River, Fort Stevens SP"
};
